development:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: mattrials
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password: